# Generated by Django 3.0.3 on 2020-07-12 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200711_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 17, 52, 124405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 17, 52, 123407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
