# Generated by Django 3.0.3 on 2020-07-14 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200711_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 9, 25, 15, 625063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 9, 25, 15, 625063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='email',
            field=models.EmailField(default='Not Given', max_length=200),
        ),
        migrations.AlterField(
            model_name='interest',
            name='phone',
            field=models.CharField(default='Not Given', max_length=10),
        ),
    ]
